### PR TITLE
drop not required comment

### PR DESCRIPTION
**Pull request by aryszka**
as it was pointed out here: https://github.com/zalando/skipper/pull/947#discussion_r255109018 , this comment is not required.

### CODE REVIEW

**Comment by szuecs** [comment]
DCO please

**Comment by mikkeloscar** [comment]
:+1:

**Comment by szuecs** [comment]
:+1:

**Comment by szuecs** [comment]
:+1:

**Comment by mikkeloscar** [comment]
:+1:

**Pull request merged**
