### PR TITLE
add monitoring info to the constructed filter instances

### PR DESCRIPTION
**Pull request by aryszka**
#40 

in one way, i find it laser. in another way, it's ugly :)
what do you think?

### CODE REVIEW

**Comment by lmineiro** [comment]
I'd prefer to name this new type to something different to make it clear. Something like RouteFilter, FilterWrapper or something else. This is only used by the proxy, isn't it?
Whoever is writing a filter will get one or the other and, eventually, use the wrong one. For those using auto-completing IDEs it can even auto-import the wrong one.

**Comment by aryszka** [comment]
i thought of this, and the argument for this name was that one always references it together with the package, like routing.Filter. but still see the point that it is not the same thing, so ok. RouteFilter is the name i hate the least.
(btw, this one is a structure, the other one is an interface, and this one even implements the other by anonymously including an instance of it, just to be precise :) )

**Comment by aryszka** [comment]
RouteFilter, it became

**Comment by lmineiro** [comment]
(y)

**Pull request merged**
