### PR TITLE
fix arm docker build targets

### PR DESCRIPTION
**Pull request by szuecs**
Signed-off-by: Sandor Szücs <sandor.szuecs@zalando.de>

### CODE REVIEW

**Comment by szuecs** [comment]
:+1:

**Comment by aryszka** [comment]
:+1:

**Comment by aryszka** [comment]
i think this actually exists: https://github.com/zalando/skipper/blob/master/packaging/Makefile#L66

what may missing is -C packaging

**Comment by szuecs** [comment]
I think it'S more readable to have not the x in buildx

**Comment by szuecs** [comment]
:+1:

**Comment by aryszka** [comment]
:+1:

**Pull request merged**
