### PR TITLE
[WIP] Filter docs

### PR DESCRIPTION
**Pull request by vetinari**
this is a list of all (non deprecated) built-in filters. Please help
to document the expected parameters and add descriptions on how to
use

### CODE REVIEW

**Comment by vetinari** [comment]
@szuecs @aryszka @mikkeloscar @lmineiro ... anyone else? ;-)

**Comment by szuecs** [comment]
@vetinari I added the rest of the filter docs, mostly based on the filter godocs.
One fix for a wrong godoc parameter is also in these commits

**Comment by vetinari** [comment]
@szuecs as said yesterday, I think the predicates should be in a different file.

**Comment by vetinari** [comment]
:+1:

**Comment by szuecs** [comment]
:+1:

**Pull request merged**
