### PR TITLE
proxy: always count route lookup failures

### PR DESCRIPTION
**Pull request by AlexanderYastrebov**
Remove debug mode check for clarity and because
other metrics are updated without checking for debug mode.

### CODE REVIEW

**Comment by szuecs** [comment]
I didn't check but if you create 404 counts for unknown hosts than it's a DoS vector for memory usage.

**Comment by AlexanderYastrebov** [comment]
> I didn't check but if you create 404 counts for unknown hosts then it's a DoS vector for memory usage.
> If it's a single counter without host cardinality then it's fine.

Yes, this metric does not have client-control dimensions (like hostname):
```console
$ bin/skipper -inline-routes='Host("foo.test") -> <shunt>' -metrics-flavour=prometheus
[APP]INFO[0000] Expose metrics in prometheus format
...
```
```console
$ curl localhost:9090
Not Found
$ curl -s localhost:9911/metrics | grep skipper_route_error_total
# HELP skipper_route_error_total The total of route lookup errors.
# TYPE skipper_route_error_total counter
skipper_route_error_total 1
```

**Comment by MustafaSaber** [comment]
👍

**Comment by AlexanderYastrebov** [comment]
:+1:

**Pull request merged**
