### PR TITLE
fix absolute minimal RG configuration example

### PR DESCRIPTION
**Pull request by Nilegfx**
fix absolute minimal RG configuration example

### CODE REVIEW

**Comment by szuecs** [comment]
The minimal version of RG depends on the jsonSchema in your cluster.

For a change we need to have signoff to fix DCO, thanks

**Comment by szuecs** [comment]
@Nilegfx we need a signoff : `git rebase -i --signoff`

**Comment by Nilegfx** [comment]
@szuecs sorry for that but I am not familiar with the signoff procedure, should I squash the two commits together and sign them? I tried without squashing but seems not wworking.

**Comment by szuecs** [comment]
You can squash while rebasing and it’s fine however you do 😊

**Comment by szuecs** [comment]
👍

**Comment by aryszka** [comment]
:+1:

**Pull request merged**
