### PR TITLE
filters/auth: allow insecure grant flow

### PR DESCRIPTION
**Pull request by AlexanderYastrebov**
Add a flag to allow insecure grant flow:
* issue token cookie without secure attribute
* use http schem for callback url

### CODE REVIEW

**Comment by MustafaSaber** [comment]
👍

**Comment by RomanZavodskikh** [comment]
In theory, Eve stealing the data between Alice (client) and Bob (server) could steal ztoken of Alice and authenticate herself as Alice, couldn't she?

**Comment by AlexanderYastrebov** [comment]
That is correct. The feature is meant for local testing.
Alternative is to run HTTPS Skipper with [self-signed certificate](https://github.com/zalando/skipper/blob/master/fixtures/gencert.sh) and ignore browser warning.

**Comment by AlexanderYastrebov** [comment]
Related https://github.com/zalando/skipper/issues/1775

**Comment by AlexanderYastrebov** [comment]
Build failed with
```
--- FAIL: TestRedisContainer (0.87s)
    redistest.go:39: Failed to start redis server: http: invalid Host header, host port waiting failed: could not start container: creating reaper failed: failed to create container
```
looks related to https://github.com/testcontainers/testcontainers-go/issues/1359

**Comment by RomanZavodskikh** [comment]
:+1:

**Comment by MustafaSaber** [comment]
👍

**Pull request merged**
