### PR TITLE
fix: default filters via configmap are not applied

### PR DESCRIPTION
**Pull request by szuecs**
fix: default filters via configmap are not applied, because we filtered symlinks

Signed-off-by: Sandor Szücs <sandor.szuecs@zalando.de>

### CODE REVIEW

**Comment by hjacobs** [comment]
Should we have a test for this?

**Comment by szuecs** [comment]
@hjacobs done

**Comment by hjacobs** [comment]
:+1:

**Comment by szuecs** [comment]
:+1:

**Pull request merged**
