### PR TITLE
serve's body= parameter accepts a table

### PR DESCRIPTION
**Pull request by vetinari**
to be rendered as JSON, requires
https://github.com/layeh/gopher-json/pull/2
to be merged

### CODE REVIEW

**Comment by vetinari** [comment]
@szuecs please tag as do-not-merge while the gopher-json PR is open

**Comment by vetinari** [comment]
upstream was updated to include the changes: https://github.com/layeh/gopher-json/commit/1aab82196e3b418b56866938f28b6a693f2c6b18#diff-2f2334e73fe2af160b1c8beb55bd3736R76

**Comment by vetinari** [comment]
:+1:

**Comment by vetinari** [comment]
@szuecs can be merged now :)

**Comment by szuecs** [comment]
:+1:

**Pull request merged**
