### PR TITLE
flag for ignoring the ingress class

### PR DESCRIPTION
**Pull request by aryszka**
added a flag to explicitly ignore the Kubernetes ingress class.

See the discussion in: #334

### CODE REVIEW

**Comment by mikkeloscar** [comment]
:+1:

**Comment by hjacobs** [comment]
I'm not sure if this makes sense for me: we might need a more generic approach, e.g. with pattern/regex matching. Why? We have the `kube-ingress-aws-controller` and `skipper` which both need to watch Ingress rules and potentially act on them, i.e. the ingress class might need to specify more than one controller and pattern matching would be the most simple and generic approach to allow both "match all" and "match a substring":

* `skipper` should be able to ignore the ingress class annotation
* `skipper` should be able to only consider Ingress resources which have the "skipper" ingress class or a list of ingress classes including "skipper" (e.g. "alb,skipper")

**Comment by slok** [comment]
I agree with @hjacobs a regex solution would be more flexible

**Comment by mikkeloscar** [comment]
lgtm

**Pull request merged**
