### PR TITLE
Add documentation for copyRequestHeader & copyResponseHeader filters

### PR DESCRIPTION
**Pull request by chellitorvic**
Currently, there are no mentions in the documentation about `copyRequestHeader` & `copyResponseHeader` filters, which makes an impression that such functionality is not implemented.

### CODE REVIEW

**Comment by szuecs** [comment]
@chellitorvic thanks! Can you do a 
`git commit --amend --signoff`, please (DCO)

**Comment by szuecs** [comment]
:+1:

**Comment by aryszka** [comment]
thanks!

**Comment by aryszka** [comment]
:+1:

**Pull request merged**
