### PR TITLE
Refactor `CloneRoute` testcase

### PR DESCRIPTION
**Pull request by MustafaSaber**
fixes https://github.com/zalando/skipper/issues/2134

### CODE REVIEW

**Comment by szuecs** [comment]
:+1:

**Comment by AlexanderYastrebov** [comment]
:+1:

**Comment by AlexanderYastrebov** [comment]
I think the whole edit/clone business would be much simpler if we serialize route to eskip, replace string and parse it back

**Comment by MustafaSaber** [comment]
Maybe we can move forward with this as standalone test cases refactor and make another issue to track the rewrite/refactor of edit/clone?

**Comment by MustafaSaber** [comment]
👍

**Pull request merged**
