### PR TITLE
Remove deprecated Route.Shunt

### PR DESCRIPTION
**Pull request by ruudk**
I see lots of deprecated stuff in the codebase that was deprecated long time ago. Maybe it's time to cleanup?

### CODE REVIEW

**Comment by szuecs** [comment]
@ruudk https://github.com/zalando/skipper/issues/432

@aryszka maybe have some PRs open and stop our automated release pipeline, before doing the breaking release, such that we have a clean v1.0.0 release?

**Comment by aryszka** [comment]
let's use this branch for these breaking changes: https://github.com/zalando/skipper/tree/release/v1

**Comment by ruudk** [comment]
Oke I changed the base. It's important that from now on, every PR that is merged to master, should also be merged to `release/v1`.

**Comment by aryszka** [comment]
> It's important that from now on, every PR that is merged to master, should also be merged to release/v1.

Agree.

**Comment by aryszka** [comment]
:+1:

**Comment by szuecs** [comment]
:+1:

**Comment by szuecs** [comment]
We can do a  `rebase master` also later

**Pull request merged**
