### PR TITLE
minor: Added OriginalRequest to the filter test utils

### PR DESCRIPTION
**Pull request by evangelion1204**
Lounge by Zalando requires the capability to easily mock `OriginalRequest` in their unit tests.

### CODE REVIEW

**Comment by AlexanderYastrebov** [comment]
Please sign-off using `git commit --amend -s`

**Comment by AlexanderYastrebov** [comment]
:+1:

**Comment by evangelion1204** [comment]
👍

**Comment by MustafaSaber** [comment]
👍

**Pull request merged**
