### PR TITLE
add route id to filter context

### PR DESCRIPTION
**Pull request by Shareed2k**
i need a way inside plugin to understand to what route, request is related. In my situation i have plugin for route policy so i need a way to fetch specific rules from service to validate the request, so the easiest way i'm see here is get route id from filter context.

[feature request](https://github.com/zalando/skipper/issues/1128)

### CODE REVIEW

**Comment by Shareed2k** [comment]
in my situation i need to implement plugin related to auth make route policy i need to create cache with routes related to specific service and i what to use route id as a key for cache and maybe also create special ratelimit rule with route id...

**Comment by szuecs** [comment]
Can you elaborate on the need of the route ID?
What do you achieve with that and why it is required?

**Comment by Shareed2k** [comment]
> Can you elaborate on the need of the route ID?
> What do you achieve with that and why it is required?
> 
> The best for this change would be to create a feature request to explain more background about this issue you solve. We have templates to guide with what information we need to understand the change better.

https://github.com/zalando/skipper/issues/1128

**Comment by szuecs** [comment]
Thanks for creating the issue.

**Comment by szuecs** [comment]
:-1:

**Comment by szuecs** [comment]
Please reopen in case the proposed solution does not work. Thanks for your understanding. #1128

**Pull request closed without merging**
