### PR TITLE
fix typo retrieable -> retrievable

### PR DESCRIPTION
**Pull request by ddufourboivin-zalando**
fix typo retrieable -> retrievable

### CODE REVIEW

**Comment by maxim-tschumak** [comment]
:+1:

**Comment by arjunrn** [comment]
:+1:

**Comment by aryszka** [comment]
Thanks for spotting this! Actually, this is not about retrieving but about retrying. So the real fix should be 'retriable' or even better 'not possible to retry'. Could you please update the PR?

**Comment by ddufourboivin-zalando** [comment]
@aryszka : There you go!

**Comment by aryszka** [comment]
:+1:

**Comment by ddufourboivin-zalando** [comment]
👍

**Pull request merged**
