### PR TITLE
minor: remove unused endpointRegistry field from healthyEndpoints and fadeIn

### PR DESCRIPTION
**Pull request by RomanZavodskikh**
Just a small removal of unsued field.

### CODE REVIEW

**Comment by AlexanderYastrebov** [comment]
I think this related is also unused https://github.com/zalando/skipper/blob/8ea6c5b58b4922c76c9936de43c73be6848cd6d5/proxy/fadein.go#L13

**Comment by RomanZavodskikh** [comment]
@AlexanderYastrebov thanks for a good catch, I have removed.

**Comment by AlexanderYastrebov** [comment]
:+1:

**Comment by MustafaSaber** [comment]
restarted pipeline

**Comment by MustafaSaber** [comment]
👍

**Comment by RomanZavodskikh** [comment]
:+1:

**Pull request merged**
