### PR TITLE
Support HTTPS requests in the Docker image

### PR DESCRIPTION
**Pull request by shuhei**
Added certificates to `Dockerfile` to support HTTPS requests. Without it, I got errors like `x509: failed to load system roots and no roots provided`.

Also:

- Updated env variables in the packaging README
- Fixed error on the first docker build

### CODE REVIEW

**Comment by hjacobs** [comment]
Thanks for the PR!

**Comment by lmineiro** [comment]
We've been mounting the host cert dir and this is how I, personally, would like to keep it.

**Comment by aryszka** [comment]
question: does having defaults prevent mounting custom ones?

**Comment by shuhei** [comment]
@lmineiro Ah, it's a good idea. But because <q>the primary use case for this docker image is to have a quick'n'dirty skipper available quick</q> according to [the packaging README](https://github.com/zalando/skipper/blob/master/packaging/readme.md), it would be great if it has default ones or documentation at least.

@Imineiro @aryszka What do you think?

**Comment by lmineiro** [comment]
@shuhei good point on the quick'n'dirty promise.
@aryszka it won't stop us from mounting but we also shouldn't really encourage using such Docker image, out of the box, for production

**Comment by ideahitme** [comment]
are we using zalando alpine image with preinstalled ca-certificates for skipper releases ? then you might just change Docker base image to registry.opensource.zalan.do/alpine and keep the same docker image for internal and external users ?

**Comment by mikkeloscar** [comment]
I think the certs should be included in the image.

One use case is running it on Kubernetes were the pod should be self-contained. You don't want to rely on where the node stores certificates, and you don't want to get `hostPath` privileges if it's not needed.

**Comment by aryszka** [comment]
sounds like a legit argument to me

**Comment by aryszka** [comment]
:+1:

**Comment by mikkeloscar** [comment]
:+1:

**Pull request merged**
