### PR TITLE
add a concurrent test case with multple routes

### PR DESCRIPTION
**Pull request by szuecs**
this should show the bug mentioned in #614 and #608.

### CODE REVIEW

**Comment by szuecs** [comment]
@aryszka sadly not, the diff for 686 calls is at most 1, which is expected and in our spec

**Comment by szuecs** [comment]
👍

**Comment by szuecs** [comment]
It complements tests, but it does not show the uneven balance from the mentioned issues

**Comment by aryszka** [comment]
:+1:

**Pull request merged**
