### PR TITLE
Adds lua benchmark

### PR DESCRIPTION
**Pull request by AlexanderYastrebov**
* Adds lua state creation benchmark
* Adds `randomPath` lua implementation and benchmark
* Adds `copyRequestHeader` lua implementation and benchmarks it against native filter
* Moves test lua scripts into canonical `testdata` folder

```
$ go test -run NONE -bench Benchmark -benchmem ./script/
goos: linux
goarch: amd64
pkg: github.com/zalando/skipper/script
cpu: Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz
BenchmarkNewState-8                         8061            144688 ns/op          180913 B/op        795 allocs/op
BenchmarkScriptRandomPath-8                79288             14569 ns/op            4032 B/op        106 allocs/op
BenchmarkScriptCopyRequestHeader-8        155889              7668 ns/op            4421 B/op         80 allocs/op
PASS
ok      github.com/zalando/skipper/script       4.758s
```
```
$ go test -run NONE -bench BenchmarkCopyRequestHeader -benchmem ./filters/builtin
goos: linux
goarch: amd64
pkg: github.com/zalando/skipper/filters/builtin
cpu: Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz
BenchmarkCopyRequestHeader-8     8454454               133.7 ns/op            21 B/op          2 allocs/op
PASS
ok      github.com/zalando/skipper/filters/builtin      1.285s
```

### CODE REVIEW

**Comment by AlexanderYastrebov** [comment]
* new state creation seems a bit expensive in terms of allocations
* lua implementation runs 60x times slower but in absolute numbers it is still microseconds

**Comment by AlexanderYastrebov** [comment]
Based on these benchmarks I think there is some room for improvement regarding allocations

**Comment by szuecs** [comment]
:+1:

**Comment by AlexanderYastrebov** [comment]
:+1:

**Pull request merged**
