### PR TITLE
Group dependabot updates 

### PR DESCRIPTION
**Pull request by szuecs**
Group dependabot updates to reduce the flood of update PRs

### CODE REVIEW

**Comment by szuecs** [comment]
:+1:

**Comment by szuecs** [comment]
Waiting for the feature 😀

**Comment by MustafaSaber** [comment]
👍

**Comment by szuecs** [comment]
:-1:

**Comment by AlexanderYastrebov** [comment]
A downside of grouping updates is that a broken update could prevent others, see e.g. https://github.com/zalando/skipper/pull/2436

**Comment by szuecs** [comment]
https://github.com/zalando/skipper/pull/3136 was merged

**Pull request closed without merging**
