### PR TITLE
HTTP->HTTPS redirect for Kubernetes

### PR DESCRIPTION
**Pull request by hjacobs**
Redirect requests with `X-Forwarded-Proto: http` and `X-Forwarded-Port: 80` to HTTPS.

### CODE REVIEW

**Comment by hjacobs** [comment]
@aryszka will fix the branch. Thanks!

**Comment by szuecs** [comment]
@hjacobs please provide a test to check the new feature

**Comment by aryszka** [comment]
@szuecs on it

**Comment by szuecs** [comment]
:+1:

**Pull request merged**
