### PR TITLE
add logging for route creation time

### PR DESCRIPTION
**Pull request by zeitlinger**
add logging for route creation time to help debugging if the issue is
1. with the route creation time logic 
2. the histogram bucket
3. or the route creation is actually slow

### CODE REVIEW

**Comment by zeitlinger** [comment]
:+1:

**Comment by tkrop** [comment]
:+1:

**Comment by tkrop** [comment]
Can we role this out to `stups-test` quickly to gain insights?

**Comment by zeitlinger** [comment]
:+1:

**Comment by zeitlinger** [comment]
> Can you please change this to debug ?

done

**Comment by szuecs** [comment]
:+1:

**Pull request merged**
