### PR TITLE
Improve fadeIn CI tests

### PR DESCRIPTION
**Pull request by RomanZavodskikh**
+ added tests for powerOfNRandomChoices monotony
+ added tests for case when all endpoints are new
+ added tests (obviously failing at the moment) for powerOfNRandomChoices to check new and old enpoints receive correct amount of requests

### CODE REVIEW

**Comment by szuecs** [comment]
:+1:

**Comment by AlexanderYastrebov** [comment]
> added tests (obviously failing at the moment) for powerOfNRandomChoices

I am confused, the build is green

**Comment by RomanZavodskikh** [comment]
> I am confused, the build is green


That's because I commented failing test not to fail the whole build because of fadeIn not added to powerOfNRandom choices (and never had been).
The test for three other algorithms (random, round-robin, consistent-hash) are green, so there were no need to comment them.

 When I will fix this problem, I will uncomment the test for powerOfNRandomChoices.

**Comment by RomanZavodskikh** [comment]
:+1:

**Comment by RomanZavodskikh** [comment]
Merging this PR because:

+ I have enough approvals
+ It does not affect production code
+ Mixed with the next PR, it may become too complex, so I better separate them

**Pull request merged**
