### PR TITLE
fix(apiusagemonitoring): add doc entry about no-op filter in case of invalid config

### PR DESCRIPTION
**Pull request by maxim-tschumak**
Related to #949

### CODE REVIEW

**Comment by maxim-tschumak** [comment]
:+1:

**Comment by aryszka** [comment]
:+1:

**Comment by maxim-tschumak** [comment]
This PR doesn't introduce any code-changes, but swarms tests are failing. @aryszka @szuecs can you please have a look?

```
--- FAIL: TestTwoSwarms (4.23s)
    --- FAIL: TestTwoSwarms/two_swarms,_few_maxhits (1.31s)
        cluster_test.go:383: 2.2 TestTwoSwarmsFewMaxHits backend allowed but should not
FAIL
FAIL	github.com/zalando/skipper/ratelimit	10.548s
/bin/sh: 1: break: Illegal number: -1
make[1]: *** [shortcheck] Error 2
make[1]: Leaving directory `/home/travis/gopath/src/github.com/zalando/skipper'
make: *** [ci-trigger] Error 2
The command "make ci-trigger" exited with 2.
```

**Comment by szuecs** [comment]
It's known https://github.com/zalando/skipper/issues/939

**Pull request merged**
