### PR TITLE
Added ID of the matching route to open tracing span

### PR DESCRIPTION
**Pull request by haldun**
- Added route ID to the proxy span.

### CODE REVIEW

**Comment by aryszka** [comment]
:+1:

**Comment by haldun** [comment]
@lmineiro you're welcome :) Btw, I changed the tag name.

**Comment by ruiaraujo** [comment]
:+1:

**Comment by lmineiro** [comment]
:+1:

**Comment by aryszka** [comment]
:+1:

**Comment by ruiaraujo** [comment]
👍

**Pull request merged**
