### PR TITLE
doc: remove video tutorial as it was outdated

### PR DESCRIPTION
**Pull request by szuecs**
doc: remove video tutorial as it was not followed up and is heavily outdated

### CODE REVIEW

**Comment by szuecs** [comment]
:+1:

**Comment by MustafaSaber** [comment]
👍

**Comment by MustafaSaber** [comment]
Maybe we can create a new one?

**Comment by AlexanderYastrebov** [comment]
:+1:

**Comment by szuecs** [comment]
@MustafaSaber let's re-think what we want to provide as content. Maybe video is a thing but I guess it would be more handy to show actual patterns of how to test and how to test your development via skipper running on your desk instead of the build. Feel free to create an issue and have some ideas there, maybe there are people that share what they miss, which would be helpful.

**Pull request merged**
