### PR TITLE
Fixes multiflag yaml parsing

### PR DESCRIPTION
**Pull request by AlexanderYastrebov**
Signed-off-by: Alexander Yastrebov <alexander.yastrebov@zalando.de>

### CODE REVIEW

**Comment by szuecs** [comment]
:+1:

**Comment by aryszka** [comment]
this just came to my mind. When we say "payload" in HTTP terms, that usually refers to the content body, while this is quite the opposite currently: it is only about the address line and the headers. I think we should rename 'payload' to something else. WDYT?

**Comment by AlexanderYastrebov** [comment]
@aryszka The argument could be made other way around: request has URL, headers and body which altogether constitute payload.

**Comment by aryszka** [comment]
in theory that completely sits. What I am talking about is what people usually think what payload is when talking about HTTP. I'll try to suggest a better name

**Comment by AlexanderYastrebov** [comment]
:+1:

**Comment by aryszka** [comment]
:+1:

**Pull request merged**
