### PR TITLE
Move pathmux

### PR DESCRIPTION
**Pull request by aryszka**
move pathmux (https://github.com/zalando/pathmux) to skipper:

- copy pathmux code under a subdirectory: pathmux/
- update the main license file to incorporate the different license and copyright

### CODE REVIEW

**Comment by LappleApple** [comment]
👍

**Comment by aryszka** [comment]
:+1:

**Comment by tv42** [comment]
The pathmux link in https://jobs.zalando.com/tech/blog/building-our-own-open-source-http-routing-solution/ is now broken.

**Comment by szuecs** [comment]
If it was because of this PR merge, then it would be quite long broken (>1 year).
I guess you want to reach someone internal and not public audience with this anyhow.

**Comment by aryszka** [comment]
thank you very much @tv42 ! We eventually updated the link. :smile:

**Pull request merged**
