### PR TITLE
cmd/eskip: fixes go1.18 vet error

### PR DESCRIPTION
**Pull request by AlexanderYastrebov**
Signed-off-by: Alexander Yastrebov <alexander.yastrebov@zalando.de>

### CODE REVIEW

**Comment by szuecs** [comment]
:+1:

**Comment by AlexanderYastrebov** [comment]
:+1:

**Comment by AlexanderYastrebov** [comment]
@szuecs lets merge this although we are not using 1.18 yet due to #1980

**Comment by mikkeloscar** [comment]
:+1:

**Pull request merged**
