### PR TITLE
Github Actions

### PR DESCRIPTION
**Pull request by ruudk**
Travis is giving me such a bad time, let's switch to Github Actions.

### CODE REVIEW

**Comment by szuecs** [comment]
:+1:

**Comment by aryszka** [comment]
:+1:

**Comment by ruudk** [comment]
Thanks for merging, now I can finalize it and make sure it works properly , will follow up

**Comment by aryszka** [comment]
i am actually fixing this now. The first issue already found. I'll share my branch with you if you want.

**Comment by ruudk** [comment]
No it’s fine you can fix it, if you need help ping me

**Pull request merged**
