### PR TITLE
benchmark tokeninfo client baseline cost

### PR DESCRIPTION
**Pull request by aryszka**
- benchmarking the network cost of calling a tokeinfo provider in ideal conditions to detect client side (as in skipper) bottlenecks
- changing the max idle connection count for the auth client. Tested with wrk1 based benchmarks
- use the same setting as the proxy for the max idle conns in the auth filters

The assumption is: setting the max idle connection count to a value similar to the proxy settings makes sense, because the usage characteristics is also similar. It should not hurt either, because the number of accessed hosts is expected to be more limited than the number of proxy backends.

Signed-off-by: Arpad Ryszka <arpad.ryszka@gmail.com>

### CODE REVIEW

**Comment by aryszka** [comment]
Example output:

```
[warmup]
Running 3s test @ http://127.0.0.1:9999/lorem.html
Requests/sec:  69297.06
Transfer/sec:     10.51MB
Running 3s test @ http://127.0.0.1:9080/lorem.html
Requests/sec:  70900.58
Transfer/sec:      7.17MB
Running 3s test @ http://127.0.0.1:9090/lorem.html
Requests/sec:  66869.37
Transfer/sec:      9.25MB
[warmup done]

[benchmarking baseline]
Running 12s test @ http://127.0.0.1:9080/lorem.html
  2 threads and 128 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     2.92ms    3.86ms  53.07ms   87.94%
    Req/Sec    32.47k     5.21k   43.53k    62.08%
  779379 requests in 12.07s, 78.79MB read
Requests/sec:  64576.84
Transfer/sec:      6.53MB
[benchmarking baseline done]

[benchmarking auth]
Running 12s test @ http://127.0.0.1:9090/lorem.html
  2 threads and 128 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     3.58ms    4.79ms  78.35ms   88.41%
    Req/Sec    26.09k     3.53k   35.12k    67.92%
  626951 requests in 12.09s, 86.70MB read
  Non-2xx or 3xx responses: 626951
Requests/sec:  51869.72
Transfer/sec:      7.17MB
[benchmarking auth done]

[all done]
```

**Comment by aryszka** [comment]
the difference is smaller when using wr2 (--rate=5400):

```
[servers started, wait 1 sec]
[APP]time="2019-08-14T12:17:17+02:00" level=info msg="Expose metrics in codahale format"
[APP]time="2019-08-14T12:17:17+02:00" level=warning msg="NewLocalRatelimit is deprecated, please use NewClientRatelimit"
[APP]time="2019-08-14T12:17:17+02:00" level=info msg="support listener on :0"
[APP]time="2019-08-14T12:17:17+02:00" level=info msg="proxy listener on :9999"
[APP]time="2019-08-14T12:17:17+02:00" level=info msg="TLS settings not found, defaulting to HTTP"
[APP]time="2019-08-14T12:17:17+02:00" level=info msg="route settings, reset, route: : * -> inlineContent(\"{\\\"scope\\\": [\\\"foo\\\", \\\"bar\\\"]}\") -> <shunt>"
[APP]time="2019-08-14T12:17:17+02:00" level=info msg="route settings received"
[APP]time="2019-08-14T12:17:17+02:00" level=info msg="route settings applied"
[APP]time="2019-08-14T12:17:17+02:00" level=info msg="Expose metrics in codahale format"
[APP]time="2019-08-14T12:17:17+02:00" level=warning msg="NewLocalRatelimit is deprecated, please use NewClientRatelimit"
[APP]time="2019-08-14T12:17:17+02:00" level=info msg="support listener on :0"
[APP]time="2019-08-14T12:17:17+02:00" level=info msg="proxy listener on :9080"
[APP]time="2019-08-14T12:17:17+02:00" level=info msg="TLS settings not found, defaulting to HTTP"
[APP]time="2019-08-14T12:17:17+02:00" level=info msg="route settings, reset, route: : * -> status(200) -> <shunt>"
[APP]time="2019-08-14T12:17:17+02:00" level=info msg="route settings received"
[APP]time="2019-08-14T12:17:17+02:00" level=info msg="route settings applied"
[APP]time="2019-08-14T12:17:17+02:00" level=info msg="Expose metrics in codahale format"
[APP]time="2019-08-14T12:17:17+02:00" level=warning msg="NewLocalRatelimit is deprecated, please use NewClientRatelimit"
[APP]time="2019-08-14T12:17:17+02:00" level=info msg="support listener on :0"
[APP]time="2019-08-14T12:17:17+02:00" level=info msg="proxy listener on :9090"
[APP]time="2019-08-14T12:17:17+02:00" level=info msg="TLS settings not found, defaulting to HTTP"
[APP]time="2019-08-14T12:17:17+02:00" level=error msg="Failed to start to ListenAndServe: listen tcp :9090: bind: address already in use"
[APP]time="2019-08-14T12:17:17+02:00" level=fatal msg="listen tcp :9090: bind: address already in use"

[warmup]
Running 3s test @ http://127.0.0.1:9999/lorem.html
Requests/sec:   4381.53
Transfer/sec:    680.33KB
Running 3s test @ http://127.0.0.1:9080/lorem.html
Requests/sec:   5136.06
Transfer/sec:    531.69KB
Running 3s test @ http://127.0.0.1:9090/lorem.html
Requests/sec:   4378.78
Transfer/sec:    786.81KB
[warmup done]

[benchmarking baseline]
Running 12s test @ http://127.0.0.1:9080/lorem.html
  2 threads and 128 connections
  Thread calibration: mean lat.: 1.716ms, rate sampling interval: 10ms
  Thread calibration: mean lat.: 2.183ms, rate sampling interval: 10ms
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.98ms    1.32ms   9.34ms   83.37%
    Req/Sec     2.86k     1.80k    7.11k    65.15%
  Latency Distribution (HdrHistogram - Recorded Latency)
 50.000%    1.61ms
 75.000%    2.28ms
 90.000%    3.70ms
 99.000%    6.91ms
 99.900%    8.52ms
 99.990%    9.10ms
 99.999%    9.35ms
100.000%    9.35ms

  Detailed Percentile spectrum:
       Value   Percentile   TotalCount 1/(1-Percentile)

       0.207     0.000000            1         1.00
       0.821     0.100000          908         1.11
       1.043     0.200000         1821         1.25
       1.240     0.300000         2724         1.43
       1.420     0.400000         3628         1.67
       1.607     0.500000         4535         2.00
       1.719     0.550000         4990         2.22
       1.835     0.600000         5443         2.50
       1.962     0.650000         5901         2.86
       2.103     0.700000         6349         3.33
       2.279     0.750000         6804         4.00
       2.385     0.775000         7030         4.44
       2.539     0.800000         7256         5.00
       2.719     0.825000         7483         5.71
       2.983     0.850000         7709         6.67
       3.323     0.875000         7937         8.00
       3.517     0.887500         8048         8.89
       3.699     0.900000         8162        10.00
       3.905     0.912500         8275        11.43
       4.207     0.925000         8388        13.33
       4.555     0.937500         8503        16.00
       4.755     0.943750         8558        17.78
       4.955     0.950000         8616        20.00
       5.183     0.956250         8672        22.86
       5.383     0.962500         8730        26.67
       5.663     0.968750         8785        32.00
       5.815     0.971875         8815        35.56
       5.943     0.975000         8843        40.00
       6.083     0.978125         8871        45.71
       6.231     0.981250         8898        53.33
       6.407     0.984375         8928        64.00
       6.527     0.985938         8941        71.11
       6.631     0.987500         8956        80.00
       6.747     0.989062         8969        91.43
       6.991     0.990625         8984       106.67
       7.183     0.992188         8998       128.00
       7.319     0.992969         9005       142.22
       7.539     0.993750         9012       160.00
       7.687     0.994531         9019       182.86
       7.795     0.995313         9026       213.33
       7.967     0.996094         9033       256.00
       8.019     0.996484         9037       284.44
       8.043     0.996875         9040       320.00
       8.135     0.997266         9044       365.71
       8.155     0.997656         9047       426.67
       8.231     0.998047         9051       512.00
       8.279     0.998242         9053       568.89
       8.399     0.998437         9054       640.00
       8.431     0.998633         9056       731.43
       8.511     0.998828         9058       853.33
       8.583     0.999023         9060      1024.00
       8.631     0.999121         9061      1137.78
       8.631     0.999219         9061      1280.00
       8.655     0.999316         9062      1462.86
       8.679     0.999414         9063      1706.67
       8.783     0.999512         9064      2048.00
       8.815     0.999561         9065      2275.56
       8.815     0.999609         9065      2560.00
       8.815     0.999658         9065      2925.71
       8.847     0.999707         9066      3413.33
       8.847     0.999756         9066      4096.00
       9.103     0.999780         9067      4551.11
       9.103     0.999805         9067      5120.00
       9.103     0.999829         9067      5851.43
       9.103     0.999854         9067      6826.67
       9.103     0.999878         9067      8192.00
       9.351     0.999890         9068      9102.22
       9.351     1.000000         9068          inf
#[Mean    =        1.980, StdDeviation   =        1.320]
#[Max     =        9.344, Total count    =         9068]
#[Buckets =           27, SubBuckets     =         2048]
----------------------------------------------------------
  61698 requests in 12.00s, 6.24MB read
Requests/sec:   5140.95
Transfer/sec:    532.17KB
[benchmarking baseline done]

[benchmarking auth]
Running 12s test @ http://127.0.0.1:9090/lorem.html
  2 threads and 128 connections
  Thread calibration: mean lat.: 2.090ms, rate sampling interval: 10ms
  Thread calibration: mean lat.: 1.740ms, rate sampling interval: 10ms
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     2.20ms    1.91ms  16.27ms   88.45%
    Req/Sec     2.84k     1.63k    7.11k    68.79%
  Latency Distribution (HdrHistogram - Recorded Latency)
 50.000%    1.62ms
 75.000%    2.35ms
 90.000%    4.50ms
 99.000%    9.63ms
 99.900%   15.13ms
 99.990%   16.11ms
 99.999%   16.28ms
100.000%   16.28ms

  Detailed Percentile spectrum:
       Value   Percentile   TotalCount 1/(1-Percentile)

       0.210     0.000000            1         1.00
       0.778     0.100000          909         1.11
       1.006     0.200000         1812         1.25
       1.213     0.300000         2722         1.43
       1.409     0.400000         3623         1.67
       1.620     0.500000         4528         2.00
       1.740     0.550000         4982         2.22
       1.867     0.600000         5434         2.50
       2.013     0.650000         5889         2.86
       2.147     0.700000         6343         3.33
       2.349     0.750000         6794         4.00
       2.497     0.775000         7019         4.44
       2.685     0.800000         7245         5.00
       2.979     0.825000         7472         5.71
       3.361     0.850000         7700         6.67
       3.833     0.875000         7924         8.00
       4.163     0.887500         8041         8.89
       4.499     0.900000         8151        10.00
       4.919     0.912500         8264        11.43
       5.303     0.925000         8377        13.33
       5.799     0.937500         8490        16.00
       6.043     0.943750         8547        17.78
       6.419     0.950000         8604        20.00
       6.763     0.956250         8660        22.86
       7.139     0.962500         8717        26.67
       7.563     0.968750         8773        32.00
       7.775     0.971875         8803        35.56
       8.071     0.975000         8832        40.00
       8.263     0.978125         8858        45.71
       8.455     0.981250         8888        53.33
       8.871     0.984375         8916        64.00
       9.103     0.985938         8929        71.11
       9.311     0.987500         8943        80.00
       9.495     0.989062         8957        91.43
       9.695     0.990625         8972       106.67
      10.127     0.992188         8986       128.00
      10.447     0.992969         8993       142.22
      11.039     0.993750         9000       160.00
      11.255     0.994531         9007       182.86
      11.679     0.995313         9014       213.33
      11.895     0.996094         9021       256.00
      12.543     0.996484         9025       284.44
      12.687     0.996875         9028       320.00
      13.263     0.997266         9032       365.71
      13.551     0.997656         9035       426.67
      13.639     0.998047         9039       512.00
      13.999     0.998242         9041       568.89
      14.167     0.998437         9042       640.00
      14.431     0.998633         9044       731.43
      14.631     0.998828         9046       853.33
      15.135     0.999023         9048      1024.00
      15.335     0.999121         9049      1137.78
      15.335     0.999219         9049      1280.00
      15.367     0.999316         9050      1462.86
      15.423     0.999414         9051      1706.67
      15.455     0.999512         9052      2048.00
      15.671     0.999561         9053      2275.56
      15.671     0.999609         9053      2560.00
      15.671     0.999658         9053      2925.71
      15.983     0.999707         9054      3413.33
      15.983     0.999756         9054      4096.00
      16.111     0.999780         9055      4551.11
      16.111     0.999805         9055      5120.00
      16.111     0.999829         9055      5851.43
      16.111     0.999854         9055      6826.67
      16.111     0.999878         9055      8192.00
      16.279     0.999890         9056      9102.22
      16.279     1.000000         9056          inf
#[Mean    =        2.198, StdDeviation   =        1.907]
#[Max     =       16.272, Total count    =         9056]
#[Buckets =           27, SubBuckets     =         2048]
----------------------------------------------------------
  61697 requests in 12.00s, 10.83MB read
  Non-2xx or 3xx responses: 61697
Requests/sec:   5141.11
Transfer/sec:      0.90MB
[benchmarking auth done]
/home/aryszka/Work/go/src/github.com/zalando/skipper/skptesting/benchmark.inc: line 48: kill: (31968) - No such process

[all done]
```

**Comment by aryszka** [comment]
with setting the idle conns to 64 (wrk1):

```
[warmup]
Running 3s test @ http://127.0.0.1:9999/lorem.html
Requests/sec:  64869.27
Transfer/sec:      9.84MB
Running 3s test @ http://127.0.0.1:9080/lorem.html
Requests/sec:  66249.80
Transfer/sec:      6.70MB
Running 3s test @ http://127.0.0.1:9090/lorem.html
Requests/sec:  20913.93
Transfer/sec:      2.11MB
[warmup done]

[benchmarking baseline]
Running 12s test @ http://127.0.0.1:9080/lorem.html
  2 threads and 128 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     3.18ms    3.78ms  46.69ms   85.55%
    Req/Sec    28.99k     3.61k   36.44k    64.58%
  Latency Distribution
     50%    1.76ms
     75%    4.95ms
     90%    8.23ms
     99%   16.46ms
  692706 requests in 12.01s, 70.03MB read
Requests/sec:  57656.86
Transfer/sec:      5.83MB
[benchmarking baseline done]

[benchmarking auth]
Running 12s test @ http://127.0.0.1:9090/lorem.html
  2 threads and 128 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     7.41ms    4.13ms  42.10ms   68.02%
    Req/Sec     8.68k   650.14    11.82k    73.75%
  Latency Distribution
     50%    7.20ms
     75%    9.91ms
     90%   12.61ms
     99%   19.13ms
  208080 requests in 12.06s, 21.03MB read
Requests/sec:  17251.79
Transfer/sec:      1.74MB
[benchmarking auth done]

[all done]
```

**Comment by aryszka** [comment]
wrk2:

(Pasting in only for reference, because pasted earlier, too, but we should ignore this result now, because apparently the processes competing for the same resources on the same machine produce strange results, as repeated tests showed.)

```
[warmup]
Running 3s test @ http://127.0.0.1:9999/lorem.html
Requests/sec:   1441.03
Transfer/sec:    223.80KB
Running 3s test @ http://127.0.0.1:9080/lorem.html
Requests/sec:   1213.33
Transfer/sec:    125.63KB
Running 3s test @ http://127.0.0.1:9090/lorem.html
Requests/sec:   1212.91
Transfer/sec:    125.55KB
[warmup done]

[benchmarking baseline]
Running 12s test @ http://127.0.0.1:9080/lorem.html
  2 threads and 128 connections
  Thread calibration: mean lat.: 3.859ms, rate sampling interval: 14ms
  Thread calibration: mean lat.: 3.819ms, rate sampling interval: 14ms
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     3.73ms    2.17ms  11.46ms   66.57%
    Req/Sec   747.45      1.25k    4.92k    81.78%
  Latency Distribution (HdrHistogram - Recorded Latency)
 50.000%    3.10ms
 75.000%    5.32ms
 90.000%    6.98ms
 99.000%    9.65ms
 99.900%   10.75ms
 99.990%   11.47ms
 99.999%   11.47ms
100.000%   11.47ms

  Detailed Percentile spectrum:
       Value   Percentile   TotalCount 1/(1-Percentile)

       0.494     0.000000            1         1.00
       1.421     0.100000          245         1.11
       1.806     0.200000          487         1.25
       2.223     0.300000          730         1.43
       2.607     0.400000          975         1.67
       3.095     0.500000         1216         2.00
       3.347     0.550000         1338         2.22
       3.623     0.600000         1460         2.50
       4.093     0.650000         1581         2.86
       4.627     0.700000         1703         3.33
       5.323     0.750000         1824         4.00
       5.611     0.775000         1887         4.44
       5.831     0.800000         1947         5.00
       6.095     0.825000         2007         5.71
       6.359     0.850000         2068         6.67
       6.635     0.875000         2128         8.00
       6.779     0.887500         2159         8.89
       6.979     0.900000         2189        10.00
       7.139     0.912500         2220        11.43
       7.255     0.925000         2250        13.33
       7.499     0.937500         2280        16.00
       7.643     0.943750         2296        17.78
       7.847     0.950000         2311        20.00
       7.995     0.956250         2326        22.86
       8.207     0.962500         2341        26.67
       8.511     0.968750         2357        32.00
       8.583     0.971875         2365        35.56
       8.719     0.975000         2372        40.00
       8.975     0.978125         2379        45.71
       9.103     0.981250         2387        53.33
       9.247     0.984375         2394        64.00
       9.327     0.985938         2399        71.11
       9.415     0.987500         2402        80.00
       9.599     0.989062         2406        91.43
       9.663     0.990625         2410       106.67
       9.727     0.992188         2413       128.00
       9.783     0.992969         2415       142.22
       9.919     0.993750         2417       160.00
      10.023     0.994531         2419       182.86
      10.079     0.995313         2421       213.33
      10.127     0.996094         2423       256.00
      10.191     0.996484         2425       284.44
      10.191     0.996875         2425       320.00
      10.247     0.997266         2426       365.71
      10.503     0.997656         2427       426.67
      10.623     0.998047         2428       512.00
      10.623     0.998242         2428       568.89
      10.735     0.998437         2429       640.00
      10.735     0.998633         2429       731.43
      10.751     0.998828         2430       853.33
      10.751     0.999023         2430      1024.00
      10.751     0.999121         2430      1137.78
      10.911     0.999219         2431      1280.00
      10.911     0.999316         2431      1462.86
      10.911     0.999414         2431      1706.67
      10.911     0.999512         2431      2048.00
      10.911     0.999561         2431      2275.56
      11.471     0.999609         2432      2560.00
      11.471     1.000000         2432          inf
#[Mean    =        3.725, StdDeviation   =        2.166]
#[Max     =       11.464, Total count    =         2432]
#[Buckets =           27, SubBuckets     =         2048]
----------------------------------------------------------
  16519 requests in 12.01s, 1.67MB read
Requests/sec:   1375.30
Transfer/sec:    142.36KB
[benchmarking baseline done]

[benchmarking auth]
Running 12s test @ http://127.0.0.1:9090/lorem.html
  2 threads and 128 connections
  Thread calibration: mean lat.: 6.885ms, rate sampling interval: 25ms
  Thread calibration: mean lat.: 2.659ms, rate sampling interval: 10ms
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     4.26ms    3.28ms  20.69ms   83.99%
    Req/Sec   783.02    570.59     2.67k    73.36%
  Latency Distribution (HdrHistogram - Recorded Latency)
 50.000%    2.78ms
 75.000%    5.81ms
 90.000%    8.98ms
 99.000%   14.97ms
 99.900%   19.02ms
 99.990%   20.70ms
 99.999%   20.70ms
100.000%   20.70ms

  Detailed Percentile spectrum:
       Value   Percentile   TotalCount 1/(1-Percentile)

       0.736     0.000000            1         1.00
       1.509     0.100000          251         1.11
       1.768     0.200000          498         1.25
       2.006     0.300000          747         1.43
       2.271     0.400000          995         1.67
       2.781     0.500000         1243         2.00
       3.279     0.550000         1368         2.22
       3.869     0.600000         1492         2.50
       4.471     0.650000         1616         2.86
       5.095     0.700000         1741         3.33
       5.807     0.750000         1865         4.00
       6.279     0.775000         1927         4.44
       6.743     0.800000         1990         5.00
       7.151     0.825000         2051         5.71
       7.675     0.850000         2116         6.67
       8.199     0.875000         2176         8.00
       8.591     0.887500         2208         8.89
       8.999     0.900000         2238        10.00
       9.471     0.912500         2269        11.43
       9.999     0.925000         2300        13.33
      10.479     0.937500         2331        16.00
      10.887     0.943750         2347        17.78
      11.183     0.950000         2362        20.00
      11.695     0.956250         2378        22.86
      12.295     0.962500         2393        26.67
      12.655     0.968750         2409        32.00
      13.023     0.971875         2417        35.56
      13.239     0.975000         2424        40.00
      13.415     0.978125         2432        45.71
      13.815     0.981250         2440        53.33
      14.135     0.984375         2448        64.00
      14.375     0.985938         2452        71.11
      14.647     0.987500         2455        80.00
      14.847     0.989062         2459        91.43
      15.119     0.990625         2463       106.67
      15.415     0.992188         2467       128.00
      15.519     0.992969         2469       142.22
      15.663     0.993750         2471       160.00
      15.839     0.994531         2473       182.86
      16.007     0.995313         2475       213.33
      16.431     0.996094         2477       256.00
      16.719     0.996484         2478       284.44
      16.815     0.996875         2479       320.00
      16.895     0.997266         2480       365.71
      17.055     0.997656         2481       426.67
      18.015     0.998047         2482       512.00
      18.015     0.998242         2482       568.89
      18.351     0.998437         2483       640.00
      18.351     0.998633         2483       731.43
      19.023     0.998828         2484       853.33
      19.023     0.999023         2484      1024.00
      19.023     0.999121         2484      1137.78
      20.095     0.999219         2485      1280.00
      20.095     0.999316         2485      1462.86
      20.095     0.999414         2485      1706.67
      20.095     0.999512         2485      2048.00
      20.095     0.999561         2485      2275.56
      20.703     0.999609         2486      2560.00
      20.703     1.000000         2486          inf
#[Mean    =        4.263, StdDeviation   =        3.280]
#[Max     =       20.688, Total count    =         2486]
#[Buckets =           27, SubBuckets     =         2048]
----------------------------------------------------------
  17172 requests in 12.01s, 1.74MB read
Requests/sec:   1429.67
Transfer/sec:    148.00KB
[benchmarking auth done]

[all done]
```

**Comment by aermakov-zalando** [comment]
👍

**Comment by aryszka** [comment]
:+1:

**Pull request merged**
