### PR TITLE
Fix ingress_controller.md  ClusterRole not enough settings.

### PR DESCRIPTION
**Pull request by masahiro331**
This pull reqeust is a modification of the document.

skipper sample yamls are not enough rbac setting.

### CODE REVIEW

**Comment by szuecs** [comment]
:+1:

**Comment by masahiro331** [comment]
👍

**Comment by szuecs** [comment]
@masahiro331 only members can approve, but thanks for the PR :)

**Comment by aryszka** [comment]
:+1:

**Pull request merged**
