### PR TITLE
shortcheck: run with -race

### LINKED ISSUE #969: enable go test -race in pipeline
https://github.com/zalando/skipper/issues/968 could be caught by the pipeline running `go test -race`.

Maybe we have an issue caused by https://github.com/golang/go/issues/24245 to enable a working race detection.

### PR DESCRIPTION
**Pull request by aermakov-zalando**
fix #969
Run tests with `-race`.

### CODE REVIEW

**Comment by szuecs** [comment]
@aryszka can you fix all these tests please?

**Comment by aryszka** [comment]
:+1:

**Comment by szuecs** [comment]
:+1:

**Comment by aryszka** [comment]
:+1:

**Pull request merged**
