### PR TITLE
Add internal tests for routing package

### PR DESCRIPTION
**Pull request by szuecs**
Add tests to show that internal function slice is behaving correctly

### CODE REVIEW

**Comment by szuecs** [comment]
As discussed in https://github.com/zalando/skipper/pull/364#pullrequestreview-50352646, I were not sure if this works correctly, so I created some tests for it

**Comment by aryszka** [comment]
thanks @szuecs . As replied in the referenced PR, it should be fine and it makes sense to me now. The tests are still useful, i'd keep them. If no objections then i just merge them.

**Comment by aryszka** [comment]
:+1:

**Comment by szuecs** [comment]
:+1:

**Pull request merged**
