### PR TITLE
Wire backend host metrics

### PR DESCRIPTION
**Pull request by aryszka**

### CODE REVIEW

**Comment by mo-gr** [comment]
👍

**Comment by hjacobs** [comment]
What does it do? We really need to document all the different metrics options, I have no clue what to use for what..

**Comment by aryszka** [comment]
I agree with improving on the doc.

This particular type of metrics does the same as the per-route or per-host metrics but for backend hosts. It collects the time to serve a request separately for each backend, method and status.

**Comment by aryszka** [comment]
@hjacobs the PR that added the metrics, but didn't wire it into the global options:

https://github.com/zalando/skipper/pull/245

**Pull request merged**
