### PR TITLE
pipeline: do not run expensive action on dependabot PRs

### PR DESCRIPTION
**Pull request by szuecs**
pipeline: do not run expensive action on dependabot PRs

### CODE REVIEW

**Comment by szuecs** [comment]
:+1:

**Comment by MustafaSaber** [comment]
👍

**Comment by szuecs** [comment]
@MustafaSaber I guess we ignore now our "required" pipelines

**Comment by AlexanderYastrebov** [comment]
:+1:

**Comment by MustafaSaber** [comment]
👍

**Pull request merged**
