### PR TITLE
Do not use endpointregistry in the hotpath

### PR DESCRIPTION
**Pull request by RomanZavodskikh**
The performance of endpointregistry under circumstances of high concurenncy is the very discussable topic, it does not seem to work perfectly at the moment.

### CODE REVIEW

**Comment by szuecs** [comment]
:+1:

**Comment by AlexanderYastrebov** [comment]
:+1:

**Comment by bocytko** [comment]
Could you also reference the commit & version that introduced this change?

**Comment by szuecs** [comment]
@bocytko it was https://github.com/zalando/skipper/pull/2645

**Pull request merged**
