### PR TITLE
Accept integers in programmatically created filter/predicate arguments. #296

### PR DESCRIPTION
**Pull request by jreyeshdez**
Modified eskip to parse numbers as int64 too.

This is a possible solution for #296 and I'd like to get feedback if it's in the right path.

### CODE REVIEW

**Comment by aryszka** [comment]
Thanks for raising this topic. Using float64 for all cases is an early design mistake on our side, and wish now the parser would have been created rather as it is in your PR.

The main issue with changing this behavior is that there can be extensions with custom filter and predicate implementations that only handle the float64 case and would get broken if such numbers would be parsed as int64 at some point. At the moment, I don't see a nice way to do this in a backwards compatible way, only with a breaking change.

A major release is something that we are planning for a while, but that should be done in a planned way that includes all the similar breaking changes like this and this means at least a couple of weeks.

If the breaking release doesn't happen early enough, would it be an OK temporary solution for your use case to parse only explicit literals to int64? E.g. `42L`? I have no better idea atm, but will think about it.

**Comment by aryszka** [comment]
opened this: https://github.com/zalando/skipper/issues/432 and referenced the topic there

**Comment by jreyeshdez** [comment]
I have tried to handle most of the scenarios as seen in the test cases, even though now all the tests go though I think this would need more testing, but it would be an OK if it is taken as a draft solution for what it could be a possible solution in future. As you have said, there are too many cases where float64 is expected.

**Comment by aryszka** [comment]
Closing this as there was no progress. The distinction between integers and floats will be introduced in a later version of the eskip syntax, probably with breaking changes.

**Pull request closed without merging**
