### PR TITLE
Add capslock for capability check

### PR DESCRIPTION
**Pull request by remychantenay**
Towards #2598 

## Summary
Adds [capslock](https://github.com/google/capslock) to highlight capabilities of Skipper's dependencies.

Output of `make capslock` attached: [capslock-skipper-output.log](https://github.com/zalando/skipper/files/12724961/capslock-skipper-output.log)

### CODE REVIEW

**Comment by AlexanderYastrebov** [comment]
:+1:

**Comment by remychantenay** [comment]
👍

**Comment by szuecs** [comment]
:+1:

**Comment by szuecs** [comment]
Thanks @remychantenay

**Pull request merged**
