### PR TITLE
rate limit support in ingress

### PR DESCRIPTION
**Pull request by szuecs**
this implements #414 rate limit support in ingress
documentation will be shown at https://godoc.org/github.com/zalando/skipper/dataclients/kubernetes

### CODE REVIEW

**Comment by aryszka** [comment]
:+1:

**Comment by hjacobs** [comment]
@szuecs no tests?

**Comment by szuecs** [comment]
Added tests

**Comment by szuecs** [comment]
@aryszka test fails metrics package:

    --- FAIL: TestProxyMetrics (0.00s)

	metrics_test.go:168: Registry contained unexpected metric for key 'allfilters.request.bar'. Found 'allfilters.combined.request'

**Comment by aryszka** [comment]
@szuecs thanks. Fixing the tests in a separate PR.

**Comment by aryszka** [comment]
👍

**Comment by szuecs** [comment]
👍

**Pull request merged**
