### PR TITLE
fix dataclient part of the "no endpoints" problem

### PR DESCRIPTION
**Pull request by szuecs**
#566 dataclient part
Make sure the port filter of getEndpoints does not result in no endpoints being used.
In case of no endpoints it will fallback to the Kubernetes service as before.

### CODE REVIEW

**Comment by aryszka** [comment]
:+1:

**Comment by szuecs** [comment]
:-1:

**Comment by szuecs** [comment]
It's more complicated than thought first. There are named ports and unnamed ports and we have to lookup services before endpoints to match the targetport from service to the endpoint port.

**Comment by szuecs** [comment]
:+1:

**Comment by aryszka** [comment]
:+1:

**Pull request merged**
