### PR TITLE
doc: latency() can also fed with time.Duration string

### PR DESCRIPTION
**Pull request by szuecs**
Signed-off-by: Sandor Szücs <sandor.szuecs@zalando.de>

### CODE REVIEW

**Comment by AlexanderYastrebov** [comment]
I think this needs a rebase on top of latest master that pins go to 1.17

**Comment by szuecs** [comment]
thanks , yeah done

**Comment by szuecs** [comment]
:+1:

**Comment by AlexanderYastrebov** [comment]
:+1:

**Pull request merged**
