### PR TITLE
fix: invalid utf-8 in grpcmessage

### PR DESCRIPTION
**Pull request by szuecs**
related issues:
- https://github.com/open-telemetry/opentelemetry-go/issues/2314
- https://github.com/golang/protobuf/issues/1228

Signed-off-by: Sandor Szücs <sandor.szuecs@zalando.de>

### CODE REVIEW

**Comment by AlexanderYastrebov** [comment]
:+1:

**Comment by AlexanderYastrebov** [comment]
Another method could be to hack lightstep tracer and embed utf-8 check into span SetTag method

**Comment by szuecs** [comment]
All values that we pass to setTag are fine, besides flowid and LogKV error values

**Comment by szuecs** [comment]
:+1:

**Pull request merged**
