### PR TITLE
Fix slack invite link

### LINKED ISSUE #1685: Slack invite in README is out of data and no longer works
**Describe the bug**
Slack invite in README is out of data and no longer works.

As a workaround: I found this working invite via reddit: https://invite.slack.golangbridge.org/

**To Reproduce**
Attempt to use the link

**Expected behavior**
The link works and allows on to join gophers.slack.com

**Observed behavior**
It says that it is expired.

### PR DESCRIPTION
**Pull request by jonathanbeber**
Fixes #1685.

### CODE REVIEW

**Comment by szuecs** [comment]
@jonathanbeber does invite work again?
The workaround I added was because maintainers provided this as a workaround.

**Comment by szuecs** [comment]
:+1:

**Comment by mikkeloscar** [comment]
:+1:

**Comment by jonathanbeber** [comment]
:+1:

**Pull request merged**
