### PR TITLE
doc: add redirectTo https example

### PR DESCRIPTION
**Pull request by szuecs**
doc: add redirectTo https example and clarify about the http to https redirect

Signed-off-by: Sandor Szücs <sandor.szuecs@zalando.de>

### CODE REVIEW

**Comment by szuecs** [comment]
:+1:

**Comment by tortila** [comment]
👍

**Comment by ruiaraujo** [comment]
:+1:

**Comment by lmineiro** [comment]
Was `Route redirect1`, in particular `redirect1` a typo?

**Pull request merged**
