### PR TITLE
test cob - continuous benchmark with routing package

### PR DESCRIPTION
**Pull request by szuecs**
test cob https://github.com/zalando/skipper/issues/1757 in a concurrent pipeline

@aryszka @AlexanderYastrebov Do we want to have this?

Signed-off-by: Sandor Szücs <sandor.szuecs@zalando.de>

### CODE REVIEW

**Comment by szuecs** [comment]
The bench failed because it shows "slower than before" in some benchmarks. Seems not very stable results, as we did not do anything that could have caused this.

**Comment by ruiaraujo** [comment]
@szuecs Cloud environments are terrible for benchmarking, to work correctly it needs some kind of correction factor applied with a known probe.

**Comment by szuecs** [comment]
@ruiaraujo yes that's true

**Comment by AlexanderYastrebov** [comment]
> Cloud environments are terrible for benchmarking, to work correctly it needs some kind of correction factor applied with a known probe.

The default threshold seems to be 20% which feels quite high already. 
Running the branch on the local machine I still get large differences up to 30%

For the purpose of catching performance regressions we may need to create special performance-regression benchmarks (or a separate package) and run only them via https://github.com/knqyf263/cob#run-only-those-benchmarks-matching-a-regular-expression

Sometimes I get results printed and sometimes not i.e. the library seems to produce unstable results.
I also do not like that library looks abandoned such that we had to fork it.

**Pull request closed without merging**
