### PR TITLE
net: update go-redis client

### PR DESCRIPTION
**Pull request by AlexanderYastrebov**
https://github.com/zalando/skipper/pull/2009 intruduced go-redis client fork that contains implementation of `ring.SetAddrs` API.

Implementation of this API with improvements was later added to the upstream so this change removes the fork.

See
* https://github.com/go-redis/redis/issues/2077
* https://github.com/zalando/skipper/pull/2009

Signed-off-by: Alexander Yastrebov <alexander.yastrebov@zalando.de>

### CODE REVIEW

**Comment by xavivars** [comment]
Moving back to a supported library instead of a temporary fork is definitely a step forward

**Comment by AlexanderYastrebov** [comment]
We wanted to perform some tests as the upstream client has active development recently.
I've also notices just now that it was moved into github.com/redis organization so it looks like it became official go client.

**Comment by AlexanderYastrebov** [comment]
> it was moved into https://github.com/redis organization so it looks like it became official go client.

https://uptrace.dev/blog/go-redis-v9.html

**Comment by szuecs** [comment]
:+1:

**Comment by AlexanderYastrebov** [comment]
:+1:

**Pull request merged**
