### PR TITLE
fix measuring the connection count in TCP-LIFO

### PR DESCRIPTION
**Pull request by aryszka**
fix measuring the connection count in cases when the server sides closes connections multiple times

Signed-off-by: Arpad Ryszka <arpad.ryszka@gmail.com>

### CODE REVIEW

**Comment by mikkeloscar** [comment]
@aryszka just to make sure I fully understand this fix. Basically before we could risk executing `case c.release <- token:` multiple times which translates to `concurrency--` on the other end: https://github.com/zalando/skipper/blob/5be4371b21b6285021857a4ccdd58d6f66dcd8d7/queuelistener/listener.go#L341

And thus we would be able to accept more connections than intended because the `concurrency` value was lower than expected.

Is this the right understanding?

**Comment by aryszka** [comment]
@mikkeloscar yes, it's exactly what happened.

I remember crawling through skipper and stdlib/net code for possibles cases where this can happen. Apparently, we were too confident that it won't happen. (Saving that synchronization step that is done now with c.once was a pretty good example of premature optimization.)

**Comment by mikkeloscar** [comment]
:+1:

**Comment by mikkeloscar** [comment]
:+1:

**Comment by aryszka** [comment]
:+1:

**Pull request merged**
