### PR TITLE
proxy: add request host to error log

### PR DESCRIPTION
**Pull request by AlexanderYastrebov**
Signed-off-by: Alexander Yastrebov <alexander.yastrebov@zalando.de>

### CODE REVIEW

**Comment by szuecs** [comment]
We log routeID which should be easy to get the host and CodeQL says it's not secure to log content from users...

**Comment by AlexanderYastrebov** [comment]
The change allows aggregating various errors by hostname. 

> We log routeID which should be easy to get the host

unless it is `_unknownroute_`

> CodeQL says it's not secure to log content from users

we log url path and user-agent just next to this

**Comment by szuecs** [comment]
Yes but unknown route doesn't matter because it will end in 404.
Or do you want to check kubernetes user errors in access logs?

**Comment by szuecs** [comment]
:+1:

**Comment by AlexanderYastrebov** [comment]
:+1:

**Pull request merged**
