### PR TITLE
filters/auth: add tokeninfo test cases

### PR DESCRIPTION
**Pull request by AlexanderYastrebov**
Add test cases and update messages for consistency.

### CODE REVIEW

**Comment by RomanZavodskikh** [comment]
Should number of tests for such pairs be equal?
+ `oauthTokeninfoAnyScope` and `oauthTokeninfoAllScope`
+ `oauthTokeninfoAnyKV` and `oauthTokeninfoAllKV`

As far as I see at the moment, they are not:
+ `oauthTokeninfoAnyScope` has 7 tests VS `oauthTokeninfoAllScope` having 4 tests
+ `oauthTokeninfoAnyKV` has 5 tests VS `oauthTokeninfoAllKV` having 6 tests

```
$ cat filters/auth/tokeninfo_test.go | grep 'msg:' | grep 'oauthTokeninfo' | cut -d':' -f2-  | tr -s ' ' 
 "oauthTokeninfoAnyScope: invalid token",
 "oauthTokeninfoAnyScope: one invalid scope",
 "oauthTokeninfoAnyScope: two invalid scopes",
 "oauthTokeninfoAnyScope: missing token",
 "oauthTokeninfoAnyScope: valid token, one valid scope",
 "oauthTokeninfoAnyScope: valid token, one valid scope, one invalid scope",
 "oauthTokeninfoAnyScope: valid token, one invalid scope, one valid scope",
 "oauthTokeninfoAllScope: valid token, all valid scopes",
 "oauthTokeninfoAllScope: valid token, two valid scopes",
 "oauthTokeninfoAllScope: valid token, one valid scope",
 "oauthTokeninfoAllScope: valid token, one valid scope, one invalid scope",
 "oauthTokeninfoAnyKV: valid token, one valid key, wrong value",
 "oauthTokeninfoAnyKV: valid token, one valid key value pair",
 "oauthTokeninfoAnyKV: valid token, one valid kv, multiple key value pairs1",
 "oauthTokeninfoAnyKV: valid token, one valid kv, multiple key value pairs2",
 "oauthTokeninfoAnyKV: valid token, one valid kv, same key multiple times should pass",
 "oauthTokeninfoAllKV: valid token, one valid key, wrong value",
 "oauthTokeninfoAllKV: valid token, one valid key value pair",
 "oauthTokeninfoAllKV: valid token, one valid key value pair, check realm",
 "oauthTokeninfoAllKV: valid token, valid key value pairs",
 "oauthTokeninfoAllKV: valid token, one valid kv, multiple key value pairs1",
 "oauthTokeninfoAllKV: valid token, one valid kv, multiple key value pairs2",
$ 
```

**Comment by AlexanderYastrebov** [comment]
> Should number of tests for such pairs be equal?

I did not want to refactor this test but rather add couple if cases I noticed while working on another change.

In principle we could add exhaustive tests like:
`anyScope: () (x y z)`
`anyScope: (a) (x y z)`
`anyScope: (a x) (x y z)`
`anyScope: (a x y) (x y z)`
`anyScope: (a x y z) (x y z)`
`anyScope: (x) (x y z)`
`anyScope: (x y) (x y z)`
`anyScope: (x y z) (x y z)`
etc

**Comment by RomanZavodskikh** [comment]
:+1:

**Comment by AlexanderYastrebov** [comment]
:+1:

**Pull request merged**
