### PR TITLE
Add filters and predicates from debug listener

### PR DESCRIPTION
**Pull request by sarslanhan**
As mentioned in the issue #222, this adds filters and predicates for the debug listener response.

### CODE REVIEW

**Comment by sarslanhan** [comment]
I am not sure why this is failing. It passes in my development env. Could we trigger a rebuild?

**Comment by mo-gr** [comment]
Tests also succeed on my machine. Seems to have something to do with the fake-etcd deps in the test. 

Looking good to me so far

**Comment by aryszka** [comment]
@mo-gr running the build. It's the etcd external proc issue. Working on a passive mock in the free time.

**Comment by aryszka** [comment]
:+1:

**Pull request merged**
