### PR TITLE
chore: Update team name in zappr

### PR DESCRIPTION
**Pull request by addityasingh**
Refer #1079, #1080

Update owning team for skipper in zappr

### CODE REVIEW

**Comment by oporkka** [comment]
:+1:

**Comment by ruiaraujo** [comment]
:+1:

**Comment by mikkeloscar** [comment]
@szuecs @aryszka are we ready for this? Biggest "impact" as I see it would be the docker image name changes, which people need to be aware of in new releases.

**Comment by hjacobs** [comment]
:+1:

**Comment by mikkeloscar** [comment]
Since this PR is from a fork, we can't verify that it works on CDP (I expect the docker push to fail because of the team change, like @szuecs pointed out about the docker image renaming).

@addityasingh do you have access to push a branch directly here? Then we could test this on CDP in the PR already.

**Comment by szuecs** [comment]
We can also take over this PR to test and change everything which is required. Right now all docs are pointing to the wrong image. This might also be coordinated with PRs to kube-ingress-aws-controller.

**Comment by addityasingh** [comment]
>@addityasingh do you have access to push a branch directly here? Then we could test this on CDP in the PR already.
I don't

**Comment by szuecs** [comment]
:+1:

**Pull request closed without merging**
