### PR TITLE
ratelimit cannot be set to 0 rate

### PR DESCRIPTION
**Pull request by aryszka**
- [x] create test to reproduce the problem
- [x] implement the fix

Signed-off-by: Arpad Ryszka <arpad.ryszka@gmail.com>

### CODE REVIEW

**Comment by AlexanderYastrebov** [comment]
If zero rate means never allow, something like
```diff
diff --git a/ratelimit/ratelimit.go b/ratelimit/ratelimit.go
index cd493c4..20eae03 100644
--- a/ratelimit/ratelimit.go
+++ b/ratelimit/ratelimit.go
@@ -398,23 +398,45 @@ func (voidRatelimit) RetryAfter(string) int      { return 0 }
 func (voidRatelimit) Delta(string) time.Duration { return -1 * time.Second }
 func (voidRatelimit) Resize(string, int)         {}
 
+type zeroRatelimit struct{}
+
+const (
+       // Delta() and RetryAfter() should return consistent values of type int64 and int respectively.
+       //
+       // News had just come over,
+       // We had five years left to cry in
+       zeroDelta time.Duration = 5 * 365 * 24 * time.Hour
+       zeroRetry int           = int(zeroDelta / time.Second)
+)
+
+func (zeroRatelimit) Allow(string) bool          { return false }
+func (zeroRatelimit) Close()                     {}
+func (zeroRatelimit) Oldest(string) time.Time    { return time.Time{} }
+func (zeroRatelimit) RetryAfter(string) int      { return zeroRetry }
+func (zeroRatelimit) Delta(string) time.Duration { return zeroDelta }
+func (zeroRatelimit) Resize(string, int)         {}
+
 func newRatelimit(s Settings, sw Swarmer, redisRing *ring) *Ratelimit {
        var impl limiter
-       switch s.Type {
-       case ServiceRatelimit:
-               impl = circularbuffer.NewRateLimiter(s.MaxHits, s.TimeWindow)
-       case LocalRatelimit:
-               log.Warning("LocalRatelimit is deprecated, please use ClientRatelimit instead")
-               fallthrough
-       case ClientRatelimit:
-               impl = circularbuffer.NewClientRateLimiter(s.MaxHits, s.TimeWindow, s.CleanInterval)
-       case ClusterServiceRatelimit:
-               s.CleanInterval = 0
-               fallthrough
-       case ClusterClientRatelimit:
-               impl = newClusterRateLimiter(s, sw, redisRing, s.Group)
-       default:
-               impl = voidRatelimit{}
+       if s.MaxHits == 0 {
+               impl = zeroRatelimit{}
+       } else {
+               switch s.Type {
+               case ServiceRatelimit:
+                       impl = circularbuffer.NewRateLimiter(s.MaxHits, s.TimeWindow)
+               case LocalRatelimit:
+                       log.Warning("LocalRatelimit is deprecated, please use ClientRatelimit instead")
+                       fallthrough
+               case ClientRatelimit:
+                       impl = circularbuffer.NewClientRateLimiter(s.MaxHits, s.TimeWindow, s.CleanInterval)
+               case ClusterServiceRatelimit:
+                       s.CleanInterval = 0
+                       fallthrough
+               case ClusterClientRatelimit:
+                       impl = newClusterRateLimiter(s, sw, redisRing, s.Group)
+               default:
+                       impl = voidRatelimit{}
+               }
        }
 
        return &Ratelimit{
```
should work

**Comment by szuecs** [comment]
My question would be if the user should not just shunt the route in case they want `zeroRatelimit`

**Comment by AlexanderYastrebov** [comment]
I have updated the PR so we can discuss (build failed due to flaky tests that is addressed by #1667)

**Comment by aryszka** [comment]
> My question would be if the user should not just shunt the route in case they want zeroRatelimit

Valid, though allowing setting the rate to 0, doesn't hurt either. One possible use case can be, when the settings are automatically generated based on some custom logic.

**Comment by aryszka** [comment]
:+1:

**Comment by szuecs** [comment]
:+1:

**Pull request merged**
