### PR TITLE
rename tee to follow conventions

### PR DESCRIPTION
**Pull request by aryszka**
also fixes some docs (the examples from the constructor can be already found in doc.go)

### CODE REVIEW

**Comment by lmineiro** [comment]
Does this break backwards compatibility?

**Comment by aryszka** [comment]
yes, it does. It's been out for 20 days. I would make here an exception from the rule, but we cal also support the capitalized variant as deprecated for a while.

**Comment by lmineiro** [comment]
Yeah, 20 days is not that long. I'd be fine with whatever approach. Your call.

**Comment by csenol** [comment]
sorry for this. I thought Path/Host/PathRegexp have this convention but now I realize the pattern. Predicates are capitalized whereas filters are all small letters. Maybe we can write this convention to somewhere if it is already not around .

**Comment by aryszka** [comment]
no worries. and yes good idea to mention the convention

**Comment by aryszka** [comment]
updated with keeping the deprecated version and documenting the naming conventions in eskip docs

**Pull request merged**
