### PR TITLE
(WIP) add methods DecCounter & GetOrRegister

### PR DESCRIPTION
**Pull request by last-ent**
GetOrRegister allows for custom metrics to be added that are not Counter or Timer.
DecCounter provides the alternative to IncCounter.

Closes https://github.com/zalando/skipper/issues/490

### CODE REVIEW

**Comment by szuecs** [comment]
Could you add tests please? :)

**Comment by lmineiro** [comment]
This approach allows different filters to override each other metric, eventually causing non-safe operations like invalid casts. This is mostly due to issues [already discussed](https://github.com/zalando/skipper/issues/352#issuecomment-310083869) and the main reason why I think this should be changed.

A filter could create a Timer for the metric with key "foo" while another "gets or registers" a Counter with the same key - "foo".

Additionally, it will also allow virtually anything to be pushed as a metric because of the 'interface{}' signature, which can break metric serialization later. For this to be manually avoided, it leaks the metrics library, which is bad.

**Comment by lmineiro** [comment]
The proposal is not calling [Register()](https://github.com/rcrowley/go-metrics/blob/master/registry.go#L129) is it? Isn't it calling [GetOrRegister()](https://github.com/rcrowley/go-metrics/blob/master/registry.go#L80) that will happily return the existing one?

**Comment by lmineiro** [comment]
I'm thinking that we could explore the [PrefixedRegistry](https://github.com/rcrowley/go-metrics/blob/master/registry.go#L149) and add one for each unique filter on registration. The added memory overhead of separate registries shouldn't be too much.

This would add more complexity to the metric serialization though, where there's already a different prefix strategy, although a global one.

**Comment by last-ent** [comment]
Ah, my mistake. You are right.
Can I suggest using another type?

```go
type CustomMetrics interface {
    metrics map[string]interface{}
    Snapshot() CustomMetrics
    Upsert(key, interface{})  // or Update
}
```

This should allow us to handle the custom metrics consistent with rest of the metrics.

**Comment by lmineiro** [comment]
I still prefer the namespacing solution. Other alternatives have the potential of runtime errors (invalid cast).

Filters shouldn't care about raw metrics and we definitely don't want to leak the metrics library to filters. This would prevent us from evolving or changing which one is used.

@last-ent would you consider contributing the prefixed registry for each filter on filter registration and the corresponding serialization? I could help with further ideas around this approach.

**Comment by last-ent** [comment]
👍

However one caveat is that I might not be able to work on this during December. If that's not going to be an issue, I am all up for it!

**Comment by lmineiro** [comment]
I think the other maintainers will agree when I say that we're thankful for your help and would be delighted if you could contribute such an improvement, regardless of the timeline.

**Comment by lmineiro** [comment]
Filter registry (at least builtin) happens [here](https://github.com/zalando/skipper/blob/master/skipper.go#L482). Seems like a reasonable place to create a filter specific Registry.

We could use a [PrefixedRegistry](https://github.com/rcrowley/go-metrics/blob/master/registry.go#L149) and hand it over to the Filter instance and, somehow appropriate, to the "/metrics" handler. We'd have to blacklist any possible prefixes already use by skipper itself.

Another alternative would be to use the normal [StandardRegistry](https://github.com/rcrowley/go-metrics/blob/master/registry.go#L58) for each filter and the metrics handler would then handle "/metrics/filterName/foo.bar" as the way to get filter specific metrics where "filterName" would be the unique filter name and "foo.bar" its own metric. The namespacing would be part of the path instead of polluting the key names.

Would be interesting to think about the implication of metrics collectors of both approaches.

**Pull request closed without merging**
