### PR TITLE
fix invalid escape sequence

### PR DESCRIPTION
**Pull request by danielseider**
fix invalid escape sequence

### CODE REVIEW

**Comment by szuecs** [comment]
@danielseider thanks for reaching out. I think it might be an issue with evaluation. Do you use shell that could evaluate the string, such that you need to double escape it?

**Comment by AlexanderYastrebov** [comment]
I think dot supposed to be escaped by backslash in regexp and backslash itself should be escaped in quoted yaml string
```
$ yamllint -d relaxed dataclients/kubernetes/deploy/apply/routegroups_crd.yaml | grep error
  110:61    error    syntax error: found unknown escape character '.'
```
so the fix seems correct.
See also http://blogs.perl.org/users/tinita/2018/03/strings-in-yaml---to-quote-or-not-to-quote.html

**Comment by szuecs** [comment]
@danielseider can you do a `git ci --amend --signoff` and force push to fix the DCO check, please?

**Comment by szuecs** [comment]
@danielseider can you squash it to one with rebase and make sure it's signed off?

https://github.com/zalando/skipper/pull/1856/commits shows 2 commits and I guess only one is signed off. DCO bot is a bit picky :( 

Thanks!

**Comment by AlexanderYastrebov** [comment]
:+1:

**Comment by szuecs** [comment]
👍

**Comment by AlexanderYastrebov** [comment]
@danielseider Thank you.

**Pull request merged**
