### PR TITLE
Fix subtree conflict

### PR DESCRIPTION
**Pull request by aryszka**
Closes https://github.com/zalando/skipper/issues/375

### CODE REVIEW

**Comment by szuecs** [comment]
@aryszka Is there a reason why you implemented the path-rewriting functions as lambda functions?
I don't see a reason, so I would argue it would be better to define them with a name.

**Comment by aryszka** [comment]
@szuecs you are right! bad reflex for sparing on argument count. Fixing this. Thx

**Comment by szuecs** [comment]
@aryszka travis job failed, otherwise lgtm

**Comment by aryszka** [comment]
:+1:

**Comment by szuecs** [comment]
:+1:

**Pull request merged**
