### PR TITLE
Support multiple files in `-routes-file`

### PR DESCRIPTION
**Pull request by ruudk**
Support multiple files in `-routes-file`

### CODE REVIEW

**Comment by szuecs** [comment]
This is a breaking change and maybe it would be better to have a `RoutesFiles`, that is used by `RoutesFile`, such that it is a non breaking change.

**Comment by ruudk** [comment]
@szuecs Hmm, but that would mean that I also have to introduce a new Config property like this?:
```golang
RoutesFile                string            `yaml:"routes-file"`
RoutesFiles              *listFlag        `yaml:"routes-files"`
```
?

That would make it a huge mess imho.

**Comment by szuecs** [comment]
@ruudk yes the other you can add a deprecation warning and add a log in case it is used with warning level, such that skipper users get a notice that they should migrate to the new flag.

**Comment by ruudk** [comment]
And how do you suggest that the CLI interface works?

**Comment by szuecs** [comment]
If possible:
`skipper -routes-file foo.eskip -routes-file bar.eskip`
or use comma separated (we have this already)
`skipper -routes-file foo.eskip,bar.eskip`

**Comment by ruudk** [comment]
@szuecs @aryszka Changed the implementation. It's now much simpler.

**Comment by szuecs** [comment]
:+1:

**Comment by aryszka** [comment]
:+1:

**Pull request merged**
