### PR TITLE
tee filter does not follow redirects if user prefers so

### PR DESCRIPTION
**Pull request by haldun**
If tee filter is created with the name `teenf`, it won't follow redirects.

### CODE REVIEW

**Comment by hjacobs** [comment]
Thanks for the PR! :smile: 

@aryszka @lmineiro does this make sense to have?

**Comment by aryszka** [comment]
@hjacobs , i think yes. I think now that the tee() filter shouldn't follow redirects by default, but we missed this aspect with the first version.

Does anyone have a good suggestion regarding the naming or using an argument for this behavior? The problem with argument would be that the tee() filter already has two optional arguments.

**Comment by aryszka** [comment]
related to https://github.com/zalando/skipper/issues/271

**Comment by aryszka** [comment]
lgtm

**Pull request merged**
