### PR TITLE
all: gofmt -s

### PR DESCRIPTION
**Pull request by ferhatelmas**
Add simplify flag to make fmt command and run it.

### CODE REVIEW

**Comment by aryszka** [comment]
@ferhatelmas thanks a lot for the PR!
Could you please also add -s to the fmt make task? https://github.com/zalando/skipper/blob/master/Makefile#L83

**Comment by ferhatelmas** [comment]
@aryszka added.

**Comment by aryszka** [comment]
👍

**Comment by aryszka** [comment]
@ferhatelmas thx, lgtm

**Comment by szuecs** [comment]
:+1:

**Pull request merged**
