### PR TITLE
routing: add debug logs

### PR DESCRIPTION
**Pull request by MustafaSaber**
Add logs in `DEBUG` level so we can later debug route table updates.

### CODE REVIEW

**Comment by szuecs** [comment]
:+1:

**Comment by RomanZavodskikh** [comment]
:+1:

**Comment by AlexanderYastrebov** [comment]
Alternatively we can create a correlation value (timestamp) for two existing messages "route settings applied" and "route settings received"

https://github.com/zalando/skipper/pull/3112

**Comment by AlexanderYastrebov** [comment]
Closing in favour of https://github.com/zalando/skipper/pull/3112

**Pull request closed without merging**
