### PR TITLE
refactor error vars in proxy to be constants

### PR DESCRIPTION
**Pull request by szuecs**
refactor error vars in proxy to be constants as described in https://dave.cheney.net/2016/04/07/constant-errors

Signed-off-by: Sandor Szuecs <sandor.szuecs@zalando.de>

### CODE REVIEW

**Comment by szuecs** [comment]
The Makefile change is to fix a bug in running LB failing tests on a mac

**Comment by szuecs** [comment]
:+1:

**Comment by szuecs** [comment]
:+1:

**Comment by aryszka** [comment]
:+1:

**Pull request merged**
