### PR TITLE
Deprecates `FilterContext.ResponseWriter()`

### PR DESCRIPTION
**Pull request by AlexanderYastrebov**
Filter implementations should use `FilterContext.Request()` to modify
backend request and `FilterContext.Response()` to modify backend response.
`FilterContext.StateBag()` could be used to transfer state between request and response filter chain phases.
`FilterContext.Serve()` could be used to serve response from the request filter chain phase.

Signed-off-by: Alexander Yastrebov <alexander.yastrebov@zalando.de>

### CODE REVIEW

**Comment by aryszka** [comment]
:+1:

**Comment by ponimas** [comment]
:+1:

**Comment by szuecs** [comment]
We should add this to the developer docs.

**Comment by AlexanderYastrebov** [comment]
@szuecs Which one do you mean? Is it https://github.com/zalando/skipper/blob/master/docs/reference/development.md
I've checked and I think the only place where `ResponseWriter()` is used or mentioned is a deprecated redirect filter https://github.com/zalando/skipper/blob/f606f7abeced67d6646cb70476168aad19f29ff2/filters/builtin/redirect.go#L186

**Pull request merged**
