### PR TITLE
Allow specifying a custom content type and response body for rate limiting

### PR DESCRIPTION
**Pull request by herojan**
Initial attempt at closing https://github.com/zalando/skipper/issues/1628, not sure if it needs more testing and documentation

### CODE REVIEW

**Comment by herojan** [comment]
Gonna close and reopen since I only changed docs so I don't think anything broke in that commit

**Comment by szuecs** [comment]
@herojan any reason why not to support it in clusterRatelimit as well?

**Comment by AlexanderYastrebov** [comment]
https://github.com/zalando/skipper/issues/1628#issuecomment-738301077

**Comment by herojan** [comment]
> any reason why not to support it in clusterRatelimit as well?

No I just wasn't sure which filters to change, will I change clientRatelimit, ratelimit, clusterRatelimit, clusterClientRatelimit?

I could also try to make the `inlineContentIfStatus` filter (which @AlexanderYastrebov pointed out in the issue) work for responses from the rate limit filters, not sure how much work that would be atm though, I think each filter ignores the other filters atm and short circuits the chain.

**Pull request closed without merging**
