### PR TITLE
Update skipper build for Go 1.13

### PR DESCRIPTION
**Pull request by mikkeloscar**
Updates skipper build for `go 1.13`

I basically ran `go mod tidy` with Go 1.13 to ensure that there are no changes to `go.mod` during build which would make the build "dirty" in git. :)

### CODE REVIEW

**Comment by mikkeloscar** [comment]
Added an update which moves the flag parsing to be called in `func main` rather than in `func init`. Without this change the following fails:

```
go test -race -test.short -run ^Test github.com/zalando/skipper/cmd/skipper
flag provided but not defined: -test.testlogfile
Usage of /tmp/go-build634583681/b001/skipper.test:
```

I'm not completely sure on the impact of this change but considering it's bad practice to do a lot of things in `init` causing problems like this, it probably makes sense :)

The `test.testlogfile` flag comes from: https://github.com/golang/go/blob/befa17c5f4591e180e5034fd4e8ca508f52dc7bc/src/cmd/go/internal/test/test.go#L1122

**Comment by szuecs** [comment]
Disabled staticcheck for now

**Comment by szuecs** [comment]
Go 1.13 has TLS1.3 https://github.com/zalando/skipper/issues/745

**Comment by szuecs** [comment]
:+1:

**Comment by mikkeloscar** [comment]
:+1:

**Pull request merged**
