### PR TITLE
Fix/go deprecations

### PR DESCRIPTION
**Pull request by szuecs**
io/ioutil is deprecated and in the PR everything was changed to the new functions, such that we have no reference to io/ioutil anymore

see also https://golang.org/doc/go1.16#ioutil

### CODE REVIEW

**Comment by AlexanderYastrebov** [comment]
Do we want to jump high to 1.17 or should settle on 1.16 maybe?

**Comment by AlexanderYastrebov** [comment]
:+1:

**Comment by szuecs** [comment]
@AlexanderYastrebov I am fine with changing it to 1.16.
wdyt @aryszka ?

**Comment by aryszka** [comment]
:+1:

**Review by aryszka — APPROVED** [review]

**Pull request merged**
