### PR TITLE
Fixes ingress apiVersion

### PR DESCRIPTION
**Pull request by AlexanderYastrebov**
Signed-off-by: Alexander Yastrebov <alexander.yastrebov@zalando.de>

### CODE REVIEW

**Comment by szuecs** [comment]
:+1:

**Comment by szuecs** [comment]
Does not really matter because we won't validate it anyways

**Comment by AlexanderYastrebov** [comment]
> Does not really matter because we won't validate it anyways

Still, less confusion if someone stumbles upon it

**Comment by AlexanderYastrebov** [comment]
:+1:

**Pull request merged**
