### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by mikkeloscar**
Update dependencies to address security vulnerabilities in modules as reported in #1756 

Also updates the import path for `gopkg.in/yaml.v2` (was `github.com/go-yaml/yaml` in some places which go modules could not understand when trying to update)

### CODE REVIEW

**Comment by szuecs** [comment]
Can you please add also the tool to our CI pipeline, such that we see it in the future?

**Comment by mikkeloscar** [comment]
We could add `snyk` like this: https://github.com/snyk/actions/tree/master/golang however it depends on a token so we need to register a user with snyk.io We can maybe use the teapot robot for this, WDYT? I could try to set it up next week, but would do it in a separate PR.

**Comment by szuecs** [comment]
Sounds great to me, if you can try to do it.

**Comment by szuecs** [comment]
👍

**Comment by jonathanbeber** [comment]
:+1:

**Pull request merged**
