### PR TITLE
add clusterfuzzlite PR fuzzing.

### PR DESCRIPTION
**Pull request by sepehrdaddev**
add [clusterfuzzlite](https://google.github.io/clusterfuzzlite/) PR fuzzing.

it uses the same code as oss-fuzz but it will trigger fuzzing on every PR and it runs for 300 seconds

### CODE REVIEW

**Comment by sepehrdaddev** [comment]
:+1:

**Comment by AlexanderYastrebov** [comment]
Won't this add 10 minutes to PR build?

**Comment by szuecs** [comment]
@sepehrdaddev that's too long maybe 2m?
It blocks the build

**Comment by sepehrdaddev** [comment]
@szuecs I'm not sure which build you are referring to the one that builds the docker images and etc run in parallel to this (in fact all the checks are running in parallel since this is a separate workflow)

as for the timing, it take about 5 mins to build the fuzzers, so I cannot change that but the remaining 10 mins I can change.

**Comment by sepehrdaddev** [comment]
I have updated the fuzz-seconds to be 300 seconds so its a bit faster.

**Comment by sepehrdaddev** [comment]
:+1:

**Comment by sepehrdaddev** [comment]
:+1:

**Pull request merged**
