### PR TITLE
Release v1 remove deprecations

### PR DESCRIPTION
**Pull request by ruudk**
Deprecations can be removed in V1.

### CODE REVIEW

**Comment by ruudk** [comment]
Test is failing because of: https://github.com/zalando/skipper/blob/a4f5cbfb764dee24b89a391e4ad5104f4f5523b6/proxy/loopback_test.go#L292-L317

Can I remove this test? I don't know what I removed to break this test, maybe @aryszka knows?

**Comment by aryszka** [comment]
@ruudk yes, this test can be removed

**Comment by aryszka** [comment]
:+1:

**Comment by szuecs** [comment]
:+1

**Comment by aryszka** [comment]
:+1:

**Pull request merged**
