### PR TITLE
minor: give more informative names to variables inside SchemeHost

### PR DESCRIPTION
**Pull request by RomanZavodskikh**
https://github.com/zalando/skipper/pull/2824#discussion_r1446049538

### CODE REVIEW

**Comment by szuecs** [comment]
The renaming feels like java. 
Variable names for locals should be single char if these are obvious like h and p. 

I don't find the right official Go documentation for this, but it comes from Go maintainers itself.

Cc @MustafaSaber

**Comment by szuecs** [comment]
:-1:

**Comment by MustafaSaber** [comment]
but `hh` doesn't seem very descriptive

**Comment by RomanZavodskikh** [comment]
It seems there's no way for this PR to be merged.

**Pull request closed without merging**
