### PR TITLE
refactor: name mutexes consistently

### PR DESCRIPTION
**Pull request by AlexanderYastrebov**
Followup on #2819

### CODE REVIEW

**Comment by MustafaSaber** [comment]
👍

**Comment by RomanZavodskikh** [comment]
minor: there's still one not renamed:
https://github.com/zalando/skipper/blob/v0.18.69/filters/auth/jwt_validation.go#L29

**Comment by RomanZavodskikh** [comment]
:+1:

**Comment by szuecs** [comment]
ah duplicated work....

**Comment by AlexanderYastrebov** [comment]
> minor: there's still one not renamed:

https://github.com/zalando/skipper/pull/2822

**Pull request merged**
