### PR TITLE
Allow non-TTY applications to execute eskip commands

### PR DESCRIPTION
**Pull request by last-ent**
ref: https://github.com/zalando/skipper/issues/449

Introduce new flag: -no-tty

### CODE REVIEW

**Comment by aryszka** [comment]
:+1:

**Comment by mikkeloscar** [comment]
Is there a use case for both reading from stdin *and* a filepath (given as argument)? Otherwise it might make sense to just not read from stdin when a filepath is passed as an argument?

**Comment by aryszka** [comment]
@last-ent what do you think about @mikkeloscar 's suggestion? Would it work for your use case? In case yes, can you please update the PR? :)

**Comment by szuecs** [comment]
@last-ent please delete also the flag in eskip to fix the build:

cmd/eskip/args.go:209: undefined: hasNoTTY

**Comment by aryszka** [comment]
:+1:

**Comment by mikkeloscar** [comment]
:+1:

**Pull request merged**
