### PR TITLE
Add step to push images to Github packages

### PR DESCRIPTION
**Pull request by MustafaSaber**
Fixes https://github.com/zalando/skipper/issues/2114

Signed-off-by: Mustafa Abdelrahman <mustafa.abdelrahman@zalando.de>

### CODE REVIEW

**Comment by MustafaSaber** [comment]
Since we pull/re-tag/push from our registry, then right now we have a race condition since both workflows will run in parallel.

**Comment by szuecs** [comment]
@MustafaSaber a simple synchronization step would be:

```bash
for i in {01..60} 
do 
    sleep 30
    origin=$(docker 2>/dev/null run registry.opensource.zalan.do/teapot/skipper:latest skipper --version | awk '{print $3}'
v0.14.3
)
   if docker pull "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.get-latest-tag.outputs.tag }}" &>/dev/null
   then
     echo "have it"
   else
     # -> we are ready to push the new version
     # push and break loop
     docker push "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.get-latest-tag.outputs.tag }}" 
     break
   fi
done
```

**Comment by szuecs** [comment]
:+1:

**Comment by szuecs** [comment]
Let's try it :)

**Comment by MustafaSaber** [comment]
👍

**Pull request merged**
