### PR TITLE
Add permissions hardening for the CI

### PR DESCRIPTION
**Pull request by demonCoder95**
Addresses https://github.com/zalando/skipper/issues/2137 by adding permissions for CI jobs for security hardening.

Signed-off-by: noor <noormuhammadmalik95@gmail.com>

### CODE REVIEW

**Comment by AlexanderYastrebov** [comment]
What is the default permission set, i.e. what does this change?

**Comment by szuecs** [comment]
@AlexanderYastrebov see the referenced issue I posted

**Comment by szuecs** [comment]
:+1:

**Comment by demonCoder95** [comment]
The default is "all permissions". @AlexanderYastrebov

**Comment by AlexanderYastrebov** [comment]
:+1:

**Pull request merged**
