### PR TITLE
858 added flowid

### PR DESCRIPTION
**Pull request by emyphan**
Closes #881

### CODE REVIEW

**Comment by szuecs** [comment]
@emyphan thanks for your PR, please see https://github.com/zalando/skipper/pull/881#issuecomment-446957006

**Comment by lmineiro** [comment]
:+1:

**Comment by lmineiro** [comment]
Thanks for adjusting

**Comment by aryszka** [comment]
:+1:

**Comment by lmineiro** [comment]
Sorry for not noticing earlier. We should use [Get()](https://golang.org/pkg/net/http/#Header.Get) instead and check against the zero value of the return.
In the current proposal, the comparison will be done case sensitive, which is not correct.

**Comment by lmineiro** [comment]
👎

**Comment by lmineiro** [comment]
:+1:

**Comment by aryszka** [comment]
:+1:

**Comment by aryszka** [comment]
thanks a lot :smile:

**Pull request merged**
