### PR TITLE
fix: filters should not hold reference to spec

### PR DESCRIPTION
**Pull request by szuecs**
Signed-off-by: Sandor Szücs <sandor.szuecs@zalando.de>

### CODE REVIEW

**Comment by aryszka** [comment]
:+1:

**Comment by tkrop** [comment]
:+1:

**Comment by tkrop** [comment]
What is the rational behind this rule?

There should not be a problem with this, since it is a reference to static singleton responsible for creating all filters.

**Comment by aryszka** [comment]
I think it's not a rule per se, just was judged to be cleaner like this..?

**Comment by szuecs** [comment]
@aryszka from my side yes, it's not a hard rule in case it makes sense to keep a reference, but the number of strings we duplicate here is limited and therefore I would rather have a little copy than a little dependency.

**Pull request merged**
