### PR TITLE
RedirectTo > Make location argument optional

### PR DESCRIPTION
**Pull request by ruudk**
This allows you to skip the `location` argument to `redirectTo`:
```diff
-redirectTo(301, "")
+redirectTo(301)
```

Much nicer, right? :)

### CODE REVIEW

**Comment by szuecs** [comment]
Thanks, lgtm!

Travis says:
```
Makefile:153: recipe for target 'check-fmt' failed
make[1]: *** [check-fmt] Error 1
```

Please run `make fmt` to fix it.

**Comment by ruudk** [comment]
@szuecs Fixed it, but it still fails. Is that related to my changes?

**Comment by szuecs** [comment]
@ruudk no, now it's https://github.com/zalando/skipper/issues/939#issuecomment-509963405

**Comment by ruudk** [comment]
That worked, it's green now!

**Comment by szuecs** [comment]
:+1:

**Comment by aryszka** [comment]
nice! thx!

**Comment by aryszka** [comment]
:+1:

**Pull request merged**
