### PR TITLE
fix build for github actions

### PR DESCRIPTION
**Pull request by aryszka**
- use local etcd binary when it's not possible to install it in GOBIN or GOPATH
- use staticcheck, gosec from the local directory 
- install redis-server for github actions

Signed-off-by: Arpad Ryszka <arpad.ryszka@gmail.com>

### CODE REVIEW

**Comment by aryszka** [comment]
@ruudk well, so far what fails, would also fail if we merged it.

Current status: failing on redis-server binary not found. https://github.com/zalando/skipper/pull/1402/checks?check_run_id=557930200

@szuecs do you know how that worked on travis?

**Comment by aryszka** [comment]
Passed! :smile:

**Comment by aryszka** [comment]
:+1:

**Comment by ruudk** [comment]
Nais :D Now lets drop Travis too! :D

**Comment by muaazsaleem** [comment]
👍

**Comment by ruudk** [comment]
When you merge this, good to remember that you make `ci/tests` required and remove the requirement for Travis in branch protection rules.

**Comment by aryszka** [comment]
:+1:

**Pull request merged**
